modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="logfilter"
version="${file.jarVersion}"
displayName="Log Filter"
description='''
按照可配置的规则过滤删除日志中输出的条目
'''

[[dependencies.logfilter]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.logfilter]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
